2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] MongoDB starting : pid=7449 port=27017 dbpath=/home/cgupta6/Downloads/TweetTrakerDB/da/data/db 64-bit host=cgupta6-VirtualBox
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] db version v3.6.3
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] allocator: tcmalloc
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] modules: none
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] build environment:
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten]     distmod: ubuntu1604
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten]     distarch: x86_64
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten]     target_arch: x86_64
2018-04-15T17:44:24.261-0700 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, storage: { dbPath: "/home/cgupta6/Downloads/TweetTrakerDB/da/data/db" }, systemLog: { destination: "file", path: "mongod.log" } }
2018-04-15T17:44:24.261-0700 W -        [initandlisten] Detected unclean shutdown - /home/cgupta6/Downloads/TweetTrakerDB/da/data/db/mongod.lock is not empty.
2018-04-15T17:44:24.288-0700 I -        [initandlisten] Detected data files in /home/cgupta6/Downloads/TweetTrakerDB/da/data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-04-15T17:44:24.288-0700 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2018-04-15T17:44:24.288-0700 I STORAGE  [initandlisten] 
2018-04-15T17:44:24.288-0700 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2018-04-15T17:44:24.288-0700 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2018-04-15T17:44:24.320-0700 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1460M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-04-15T17:44:26.065-0700 I STORAGE  [initandlisten] WiredTiger message [1523839466:65622][7449:0x7f73efc399c0], txn-recover: Main recovery loop: starting at 81/7410048
2018-04-15T17:44:26.067-0700 I STORAGE  [initandlisten] WiredTiger message [1523839466:67138][7449:0x7f73efc399c0], txn-recover: Recovering log 81 through 82
2018-04-15T17:44:26.258-0700 I STORAGE  [initandlisten] WiredTiger message [1523839466:258446][7449:0x7f73efc399c0], txn-recover: Recovering log 82 through 82
2018-04-15T17:44:26.882-0700 I CONTROL  [initandlisten] 
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] 
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-04-15T17:44:26.883-0700 I CONTROL  [initandlisten] 
2018-04-15T17:44:27.118-0700 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/home/cgupta6/Downloads/TweetTrakerDB/da/data/db/diagnostic.data'
2018-04-15T17:44:27.121-0700 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-04-15T17:44:28.091-0700 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2018-04-15T17:45:40.919-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:56322 #1 (1 connection now open)
2018-04-15T17:45:40.936-0700 I NETWORK  [conn1] received client metadata from 127.0.0.1:56322 conn: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "Ubuntu 16.04 xenial", architecture: "x86_64", version: "4.13.0-38-generic" }, platform: "CPython 2.7.12.final.0" }
2018-04-15T17:45:40.941-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:56324 #2 (2 connections now open)
2018-04-15T17:45:40.941-0700 I NETWORK  [conn2] received client metadata from 127.0.0.1:56324 conn: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "Ubuntu 16.04 xenial", architecture: "x86_64", version: "4.13.0-38-generic" }, platform: "CPython 2.7.12.final.0" }
2018-04-15T17:45:41.027-0700 I ACCESS   [conn2] Successfully authenticated as principal twtuser on tweettracker
2018-04-15T17:45:41.029-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:56326 #3 (3 connections now open)
2018-04-15T17:45:41.033-0700 I NETWORK  [conn3] received client metadata from 127.0.0.1:56326 conn: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "Ubuntu 16.04 xenial", architecture: "x86_64", version: "4.13.0-38-generic" }, platform: "CPython 2.7.12.final.0" }
2018-04-15T17:45:41.034-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:56328 #4 (4 connections now open)
2018-04-15T17:45:41.035-0700 I NETWORK  [conn4] received client metadata from 127.0.0.1:56328 conn: { driver: { name: "PyMongo", version: "3.6.1" }, os: { type: "Linux", name: "Ubuntu 16.04 xenial", architecture: "x86_64", version: "4.13.0-38-generic" }, platform: "CPython 2.7.12.final.0" }
2018-04-15T17:45:41.056-0700 I ACCESS   [conn4] Successfully authenticated as principal twtuser on tweettracker
2018-04-15T17:47:05.891-0700 I COMMAND  [conn2] insert tweettracker.tweets ninserted:2744 keysInserted:8232 numYields:0 locks:{ Global: { acquireCount: { r: 43, w: 43 } }, Database: { acquireCount: { w: 43 } }, Collection: { acquireCount: { w: 43 } } } 1126ms
2018-04-15T17:47:06.028-0700 I COMMAND  [conn4] insert tweettracker.tweets ninserted:0 writeConflicts:61 exception: E11000 duplicate key error collection: tweettracker.tweets index: _id_ dup key: { : ObjectId('5ad3f2881d7dfb1d6697d4af') } code:DuplicateKey numYields:0 locks:{ Global: { acquireCount: { r: 2848, w: 2848 } }, Database: { acquireCount: { w: 2848 } }, Collection: { acquireCount: { w: 2848 } } } 749ms
2018-04-15T17:48:16.737-0700 I COMMAND  [conn2] insert tweettracker.tweets ninserted:1518 keysInserted:4627 exception: E11000 duplicate key error collection: tweettracker.tweets index: catime_1_id_1 dup key: { : 6660061523839609, : 985680878721478658 } code:DuplicateKey numYields:0 locks:{ Global: { acquireCount: { r: 34, w: 34 } }, Database: { acquireCount: { w: 34 } }, Collection: { acquireCount: { w: 34 } } } 166ms
2018-04-15T17:48:17.334-0700 I COMMAND  [conn4] insert tweettracker.tweets ninserted:0 keysInserted:18 exception: E11000 duplicate key error collection: tweettracker.tweets index: _id_ dup key: { : ObjectId('5ad3f2cf1d7dfb1d6697daa7') } code:DuplicateKey numYields:0 locks:{ Global: { acquireCount: { r: 1551, w: 1551 } }, Database: { acquireCount: { w: 1551 } }, Collection: { acquireCount: { w: 1551 } } } 416ms
2018-04-15T17:49:23.621-0700 I COMMAND  [conn2] insert tweettracker.tweets ninserted:2149 keysInserted:6752 exception: E11000 duplicate key error collection: tweettracker.tweets index: catime_1_id_1 dup key: { : 3330191523839682, : 985681186772008960 } code:DuplicateKey numYields:0 locks:{ Global: { acquireCount: { r: 46, w: 46 } }, Database: { acquireCount: { w: 46 } }, Collection: { acquireCount: { w: 46 } } } 268ms
2018-04-15T17:49:24.378-0700 I COMMAND  [conn4] insert tweettracker.tweets ninserted:0 keysInserted:9 exception: E11000 duplicate key error collection: tweettracker.tweets index: _id_ dup key: { : ObjectId('5ad3f3131d7dfb1d6697e316') } code:DuplicateKey numYields:0 locks:{ Global: { acquireCount: { r: 2192, w: 2192 } }, Database: { acquireCount: { w: 2192 } }, Collection: { acquireCount: { w: 2192 } } } 556ms
2018-04-15T17:49:58.602-0700 I NETWORK  [conn4] end connection 127.0.0.1:56328 (3 connections now open)
2018-04-15T17:49:58.604-0700 I NETWORK  [conn3] end connection 127.0.0.1:56326 (2 connections now open)
2018-04-15T17:49:58.604-0700 I NETWORK  [conn2] end connection 127.0.0.1:56324 (1 connection now open)
2018-04-15T17:49:58.604-0700 I NETWORK  [conn1] end connection 127.0.0.1:56322 (0 connections now open)
